#!/usr/bin/env zsh

_wt_operation() {
  echo "${words[2]}"
}

_wt_number_of_args() {
  echo "$#words"
}

_wt_add_operation_completions() {
    local options

    [[ "$(_wt_number_of_args)" = "3" ]] && options=("new-branch: The name of the new branch you want to create")

    [[ "$(_wt_number_of_args)" = "4" ]] && options=("remote-branch: The name of the remote branch that we want to check out")

    _describe "operations" options
}

_wt_default_completions() {
    local operations

    operations=(
        "list: List details of each working tree. Press ESC to exit or select a worktree to move into it"
        "prune: Prune working tree information"
        "fetch: Fetch branches from the bare repository"
        "add: Create new working tree"
        "remove: Remove a working tree"
        "clean: Remove all working trees that do not have a corresponding remote branch"
        "upgrade: Upgrade zsh-git-worktree plugin"
    )

    _describe "operations" operations
}

_wt() {
    case "$(_wt_operation)" in
        add)
        _wt_add_operation_completions
        ;;
    esac

    [[ "$(_wt_number_of_args)" = "2" ]] &&  _wt_default_completions
}

compdef _wt wt
