#!/usr/bin/env bash

colorful_echo() {
    GREEN="\033[0;32m"
    RED="\033[0;31m"
    NC="\033[0m" # No Color

    if [ "$#" -eq 1 ]; then
        echo -e $1
    elif [ "$2" = "GREEN" ]; then
        echo -e "${GREEN}$1${NC}"
    elif [ "$2" = "RED" ]; then
        echo -e "${RED}$1${NC}"
    fi
}

colorful_echo "Install fzf\n" "GREEN"

if [ -d ~/.fzf ] ; then
    pushd ~/.fzf > /dev/null
    git pull
    ./install
    popd > /dev/null
else
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install
fi

colorful_echo "Install zsh-git-worktree plugin\n" "GREEN"

if [ -d ~/.oh-my-zsh/custom/plugins/zsh-git-worktree ] ; then
    pushd ~/.oh-my-zsh/custom/plugins/zsh-git-worktree > /dev/null
    git pull
    colorful_echo "Restart your shell or reload config file(.zshrc)." "GREEN"
    popd > /dev/null
else
    # git clone https://github.com/alexiszamanidis/zsh-git-worktree.git ~/.oh-my-zsh/custom/plugins/zsh-git-worktree
    colorful_echo "Add plugin to plugin list:" "GREEN"
    colorful_echo "- Open .zshrc(e.g. code .zshrc, vim .zshrc)"
    colorful_echo " - Add plugin to plugin list: 'plugins=(zsh-git-worktree)'"
fi
