#!/usr/bin/env bash

source ~/.oh-my-zsh/custom/plugins/zsh-git-worktree/helpers

colorful_echo "Install fzf\n" "GREEN"

if [ -d ~/.fzf ] ; then
    pushd ~/.fzf > /dev/null
    git pull
    ./install
    popd > /dev/null
else
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install
fi

colorful_echo "Install zsh-git-worktree plugin\n" "GREEN"

if [ -d ~/.oh-my-zsh/custom/plugins/zsh-git-worktree ] ; then
    pushd ~/.oh-my-zsh/custom/plugins/zsh-git-worktree > /dev/null
    git pull
    colorful_echo "Restart your shell or reload config file(.zshrc)." "GREEN"
    popd > /dev/null
else
    git clone https://github.com/alexiszamanidis/zsh-git-worktree.git ~/.oh-my-zsh/custom/plugins/zsh-git-worktree
    colorful_echo "Add plugin to plugin list:" "GREEN"
    colorful_echo "- Open .zshrc(e.g. code .zshrc, vim .zshrc)"
    colorful_echo " - Add plugin to plugin list: 'plugins=(zsh-git-worktree)'"
fi
