#!/usr/bin/env bash

_branch() {
    git rev-parse HEAD > /dev/null 2>&1 || return

    git branch --color=always --all --sort=-committerdate |
    grep -v HEAD              | # filter out any branches branches with HEAD in it
    fzf --ansi --no-preview   | # do not parse ansi codes
    sed "s/.* //"               # remove the asterisk and leading whitespace
}
