#!/usr/bin/env bash

source "$(dirname "$0")/branch"

_checkout() {
    local BRANCH=$(_branch)

    [[ "$BRANCH" = "" ]] && return

    if [[ "$BRANCH" = 'remotes/'* ]]; then
        git checkout --track $BRANCH
    else
        git checkout $BRANCH;
    fi

    local CURRENT_PATH=$PWD

    _checkout_hook $BRANCH $PWD
}

_checkout_hook() {
    _fn_exists zsh_git_fzf_on_checkout
    if [ $? -eq 0 ]; then
        zsh_git_fzf_on_checkout $@
    fi
}
