#!/usr/bin/env bash

source "$(dirname "$0")/../../src/operations/branch"

_checkout() {
    local branch=$(_branch)

    [[ "$branch" = "" ]] && return

    if [[ "$branch" = 'remotes/'* ]]; then
        git checkout --track $branch
    else
        git checkout $branch;
    fi
}
